import { ref } from "vue";

export const dataSearch = ref([
  {
    id: 1,
    deviceCode: "PT2012",
    deviceName: "Xe tải 5T - 29G1 123.45",
    rowChiSo: [
      {
        code: "P",
        name: "Công suất",
        unit: "Kw",
        accumulation: false,
        actual: "4800",
        time: new Date(),
      },
      {
        code: "V",
        name: "Điện áp",
        unit: "V",
        accumulation: false,
        actual: "220",
        time: new Date(),
      },
      {
        code: "A",
        name: "Dòng điện",
        unit: "A",
        accumulation: false,
        actual: "22",
        time: new Date(),
      },
      {
        code: "T",
        name: "Nhiệt độ",
        unit: "°C",
        accumulation: false,
        actual: "35",
        time: new Date(),
      },
      {
        code: "F",
        name: "Tần số",
        unit: "Hz",
        accumulation: false,
        actual: "50",
        time: new Date(),
      },
    ],
    rowTime: [
      {
        isActive: true,
        from: "00:00",
        to: "24:00",
        reason: "Thủng lốp",
      },
      {
        isActive: false,
        from: "00:00",
        to: "24:00",
        reason: "Hỏng hóc",
      },
      {
        isActive: true,
        from: "08:00",
        to: "12:00",
        reason: "Bảo dưỡng định kỳ",
      },
      {
        isActive: true,
        from: "13:00",
        to: "17:00",
        reason: "Thay thế phụ tùng",
      },
      {
        isActive: false,
        from: "07:00",
        to: "19:00",
        reason: "Sửa chữa động cơ",
      },
    ],
    rowNhienLieu: [
      {
        type: "Dầu",
        consumption: "100",
        unit: "lít",
      },
      {
        type: "Xăng",
        consumption: "80",
        unit: "lít",
      },
      {
        type: "Gas",
        consumption: "50",
        unit: "kg",
      },
      {
        type: "Điện",
        consumption: "200",
        unit: "kWh",
      },
      {
        type: "Nước",
        consumption: "150",
        unit: "m³",
      },
    ],
  },
  {
    id: 2,
    deviceCode: "PT2013",
    deviceName: "Xe tải 5T - 29G1 123.45",
    rowChiSo: [
      {
        code: "P",
        name: "Công suất",
        unit: "Kw",
        accumulation: false,
        actual: "4800",
        time: new Date(),
      },
      {
        code: "V",
        name: "Điện áp",
        unit: "V",
        accumulation: false,
        actual: "220",
        time: new Date(),
      },
      {
        code: "A",
        name: "Dòng điện",
        unit: "A",
        accumulation: false,
        actual: "22",
        time: new Date(),
      },
      {
        code: "T",
        name: "Nhiệt độ",
        unit: "°C",
        accumulation: false,
        actual: "35",
        time: new Date(),
      },
      {
        code: "F",
        name: "Tần số",
        unit: "Hz",
        accumulation: false,
        actual: "50",
        time: new Date(),
      },
    ],
    rowTime: [
      {
        isActive: true,
        from: "00:00",
        to: "24:00",
        reason: "Thủng lốp",
      },
      {
        isActive: false,
        from: "00:00",
        to: "24:00",
        reason: "Hỏng hóc",
      },
      {
        isActive: true,
        from: "08:00",
        to: "12:00",
        reason: "Bảo dưỡng định kỳ",
      },
      {
        isActive: true,
        from: "13:00",
        to: "17:00",
        reason: "Thay thế phụ tùng",
      },
      {
        isActive: false,
        from: "07:00",
        to: "19:00",
        reason: "Sửa chữa động cơ",
      },
    ],
    rowNhienLieu: [
      {
        type: "Dầu",
        consumption: "100",
        unit: "lít",
      },
      {
        type: "Xăng",
        consumption: "80",
        unit: "lít",
      },
      {
        type: "Gas",
        consumption: "50",
        unit: "kg",
      },
      {
        type: "Điện",
        consumption: "200",
        unit: "kWh",
      },
      {
        type: "Nước",
        consumption: "150",
        unit: "m³",
      },
    ],
  },
  {
    id: 3,
    deviceCode: "PT2014",
    deviceName: "Xe tải 5T - 29G1 123.45",
    rowChiSo: [
      {
        code: "P",
        name: "Công suất",
        unit: "Kw",
        accumulation: false,
        actual: "4800",
        time: new Date(),
      },
      {
        code: "V",
        name: "Điện áp",
        unit: "V",
        accumulation: false,
        actual: "220",
        time: new Date(),
      },
      {
        code: "A",
        name: "Dòng điện",
        unit: "A",
        accumulation: false,
        actual: "22",
        time: new Date(),
      },
      {
        code: "T",
        name: "Nhiệt độ",
        unit: "°C",
        accumulation: false,
        actual: "35",
        time: new Date(),
      },
      {
        code: "F",
        name: "Tần số",
        unit: "Hz",
        accumulation: false,
        actual: "50",
        time: new Date(),
      },
    ],
    rowTime: [
      {
        isActive: true,
        from: "00:00",
        to: "24:00",
        reason: "Thủng lốp",
      },
      {
        isActive: false,
        from: "00:00",
        to: "24:00",
        reason: "Hỏng hóc",
      },
      {
        isActive: true,
        from: "08:00",
        to: "12:00",
        reason: "Bảo dưỡng định kỳ",
      },
      {
        isActive: true,
        from: "13:00",
        to: "17:00",
        reason: "Thay thế phụ tùng",
      },
      {
        isActive: false,
        from: "07:00",
        to: "19:00",
        reason: "Sửa chữa động cơ",
      },
    ],
    rowNhienLieu: [
      {
        type: "Dầu",
        consumption: "100",
        unit: "lít",
      },
      {
        type: "Xăng",
        consumption: "80",
        unit: "lít",
      },
      {
        type: "Gas",
        consumption: "50",
        unit: "kg",
      },
      {
        type: "Điện",
        consumption: "200",
        unit: "kWh",
      },
      {
        type: "Nước",
        consumption: "150",
        unit: "m³",
      },
    ],
  },
]);

export const columnsChiSo = [
  {
    name: "code",
    label: "Mã thông số",
    field: "code",
    align: "left",
  },
  {
    name: "name",
    label: "Tên thông số",
    field: "name",
    align: "left",
  },
  {
    name: "unit",
    label: "Đơn vị",
    field: "unit",
    align: "left",
  },
  {
    name: "accumulation",
    label: "Tích lũy",
    field: "accumulation",
    align: "left",
  },
  {
    name: "actual",
    label: "Thực tế",
    field: "actual",
    align: "left",
  },
  {
    type: "date",
    name: "time",
    label: "Thời gian",
    field: "time",
    align: "left",
  },
];

export const columnsTime = [
  {
    name: "isActive",
    label: "Trạng thái",
    align: "left",
    field: "isActive",
  },
  {
    name: "from",
    label: "Từ",
    align: "left",
    field: "from",
  },
  {
    name: "to",
    align: "left",
    label: "Đến",
    field: "to",
  },
  {
    name: "reason",
    align: "left",
    label: "Lý do",
    field: "reason",
  },
];

export const columnsNhienLieu = [
  {
    name: "type",
    label: "Loại nhiên liệu",
    align: "left",
    field: "type",
  },
  {
    name: "consumption",
    label: "Số lượng tiêu thụ",
    align: "left",
    field: "consumption",
  },
  {
    name: "unit",
    align: "left",
    label: "Đơn vị",
    field: "unit",
  },
];

export const dataShift = ref([
  {
    id: 1,
    date: new Date(),
    startTime: new Date("2023-01-01T08:00:00"),
    endTime: new Date("2023-01-01T16:00:00"),
    status: true,
    unit: "Phòng kỹ thuật",
    employee: "Nguyễn Văn A",
    position: "Kỹ sư vận hành",
  },
  {
    id: 2,
    date: new Date(),
    startTime: new Date("2023-01-01T16:00:00"),
    endTime: new Date("2023-01-02T00:00:00"),
    status: true,
    unit: "Phòng kỹ thuật",
    employee: "Trần Văn B",
    position: "Kỹ sư vận hành",
  },
  {
    id: 3,
    date: new Date(new Date().setDate(new Date().getDate() - 1)),
    startTime: new Date("2023-01-01T08:00:00"),
    endTime: new Date("2023-01-01T16:00:00"),
    status: false,
    unit: "Phòng kỹ thuật",
    employee: "Lê Thị C",
    position: "Kỹ sư vận hành",
  },
  {
    id: 4,
    date: new Date(new Date().setDate(new Date().getDate() - 1)),
    startTime: new Date("2023-01-01T16:00:00"),
    endTime: new Date("2023-01-02T00:00:00"),
    status: false,
    unit: "Phòng kỹ thuật",
    employee: "Phạm Văn D",
    position: "Kỹ sư vận hành",
  },
  {
    id: 5,
    date: new Date(new Date().setDate(new Date().getDate() - 2)),
    startTime: new Date("2023-01-01T08:00:00"),
    endTime: new Date("2023-01-01T16:00:00"),
    status: false,
    unit: "Phòng bảo trì",
    employee: "Hoàng Văn E",
    position: "Kỹ thuật viên",
  },
  {
    id: 6,
    date: new Date(new Date().setDate(new Date().getDate() - 2)),
    startTime: new Date("2023-01-01T16:00:00"),
    endTime: new Date("2023-01-02T00:00:00"),
    status: false,
    unit: "Phòng bảo trì",
    employee: "Ngô Thị F",
    position: "Kỹ thuật viên",
  },
  {
    id: 7,
    date: new Date(new Date().setDate(new Date().getDate() - 3)),
    startTime: new Date("2023-01-01T08:00:00"),
    endTime: new Date("2023-01-01T16:00:00"),
    status: false,
    unit: "Phòng sản xuất",
    employee: "Đỗ Văn G",
    position: "Nhân viên vận hành",
  },
  {
    id: 8,
    date: new Date(new Date().setDate(new Date().getDate() - 3)),
    startTime: new Date("2023-01-01T16:00:00"),
    endTime: new Date("2023-01-02T00:00:00"),
    status: false,
    unit: "Phòng sản xuất",
    employee: "Vũ Thị H",
    position: "Nhân viên vận hành",
  },
  {
    id: 9,
    date: new Date(new Date().setDate(new Date().getDate() - 4)),
    startTime: new Date("2023-01-01T08:00:00"),
    endTime: new Date("2023-01-01T16:00:00"),
    status: false,
    unit: "Phòng kỹ thuật",
    employee: "Bùi Văn I",
    position: "Kỹ sư vận hành",
  },
  {
    id: 10,
    date: new Date(new Date().setDate(new Date().getDate() - 4)),
    startTime: new Date("2023-01-01T16:00:00"),
    endTime: new Date("2023-01-02T00:00:00"),
    status: false,
    unit: "Phòng kỹ thuật",
    employee: "Lý Thị K",
    position: "Kỹ sư vận hành",
  },
  {
    id: 11,
    date: new Date(new Date().setDate(new Date().getDate() - 5)),
    startTime: new Date("2023-01-01T08:00:00"),
    endTime: new Date("2023-01-01T16:00:00"),
    status: false,
    unit: "Phòng bảo trì",
    employee: "Trương Văn L",
    position: "Kỹ thuật viên",
  },
  {
    id: 12,
    date: new Date(new Date().setDate(new Date().getDate() - 5)),
    startTime: new Date("2023-01-01T16:00:00"),
    endTime: new Date("2023-01-02T00:00:00"),
    status: false,
    unit: "Phòng bảo trì",
    employee: "Đinh Thị M",
    position: "Kỹ thuật viên",
  },
  {
    id: 13,
    date: new Date(new Date().setDate(new Date().getDate() - 6)),
    startTime: new Date("2023-01-01T08:00:00"),
    endTime: new Date("2023-01-01T16:00:00"),
    status: false,
    unit: "Phòng sản xuất",
    employee: "Phan Văn N",
    position: "Nhân viên vận hành",
  },
  {
    id: 14,
    date: new Date(new Date().setDate(new Date().getDate() - 6)),
    startTime: new Date("2023-01-01T16:00:00"),
    endTime: new Date("2023-01-02T00:00:00"),
    status: false,
    unit: "Phòng sản xuất",
    employee: "Huỳnh Thị P",
    position: "Nhân viên vận hành",
  },
  {
    id: 15,
    date: new Date(new Date().setDate(new Date().getDate() - 7)),
    startTime: new Date("2023-01-01T08:00:00"),
    endTime: new Date("2023-01-01T16:00:00"),
    status: false,
    unit: "Phòng kỹ thuật",
    employee: "Võ Văn Q",
    position: "Kỹ sư vận hành",
  },
  {
    id: 16,
    date: new Date(new Date().setDate(new Date().getDate() - 7)),
    startTime: new Date("2023-01-01T16:00:00"),
    endTime: new Date("2023-01-02T00:00:00"),
    status: false,
    unit: "Phòng kỹ thuật",
    employee: "Dương Thị R",
    position: "Kỹ sư vận hành",
  },
  {
    id: 17,
    date: new Date(new Date().setDate(new Date().getDate() - 8)),
    startTime: new Date("2023-01-01T08:00:00"),
    endTime: new Date("2023-01-01T16:00:00"),
    status: false,
    unit: "Phòng bảo trì",
    employee: "Hồ Văn S",
    position: "Kỹ thuật viên",
  },
  {
    id: 18,
    date: new Date(new Date().setDate(new Date().getDate() - 8)),
    startTime: new Date("2023-01-01T16:00:00"),
    endTime: new Date("2023-01-02T00:00:00"),
    status: false,
    unit: "Phòng bảo trì",
    employee: "Trịnh Thị T",
    position: "Kỹ thuật viên",
  },
  {
    id: 19,
    date: new Date(new Date().setDate(new Date().getDate() - 9)),
    startTime: new Date("2023-01-01T08:00:00"),
    endTime: new Date("2023-01-01T16:00:00"),
    status: false,
    unit: "Phòng sản xuất",
    employee: "Lương Văn U",
    position: "Nhân viên vận hành",
  },
  {
    id: 20,
    date: new Date(new Date().setDate(new Date().getDate() - 9)),
    startTime: new Date("2023-01-01T16:00:00"),
    endTime: new Date("2023-01-02T00:00:00"),
    status: false,
    unit: "Phòng sản xuất",
    employee: "Mai Thị V",
    position: "Nhân viên vận hành",
  },
]);

export const dataCa = ref([]);


export const columnsThongSo = [
    {
      name: "code",
      label: "Mã thông số",
      field: "code",
      align: "left",
    },
    {
      name: "name",
      label: "Tên thông số",
      field: "name",
      align: "left",
    },
    {
      name: "unit",
      label: "Đơn vị",
      field: "unit",
      align: "left",
    },
    {
      name: "accumulation",
      label: "Tích lũy",
      field: "accumulation",
      align: "left",
    },
    {
      name: "actual",
      label: "Thực tế",
      field: "actual",
      align: "left",
    },
    {
      type: "date",
      name: "time",
      label: "Thời gian",
      field: "time",
      align: "left",
    },
    {
      name: "action",
      align: "left",
      label: "Hành động",
      field: "action",
    },
  ];
export const columnsTrangThai = [
  {
    name: "isActive",
    label: "Trạng thái",
    align: "left",
    field: "isActive",
  },
  {
    name: "from",
    label: "Từ",
    align: "left",
    field: "from",
  },
  {
    name: "to",
    align: "left",
    label: "Đến",
    field: "to",
  },
  {
    name: "type",
    align: "left",
    label: "Loại sự cố",
    field: "type",
  },
  {
    name: "action",
    align: "left",
    label: "Hành động",
    field: "action",
  },
  
];

export const columnsNhienLieu2 = [
    {
      name: "code",
      label: "Mã nhiên liệu",
      align: "left",
      field: "code",
    },
    {
      name: "type",
      label: "Loại nhiên liệu",
      align: "left",
      field: "type",
    },
    {
      name: "consumption",
      align: "left",
      label: "Số lượng tiêu thụ",
      field: "consumption",
    },
    {
      name: "unit",
      align: "left",
      label: "Đơn vị",
      field: "unit",
    },
    {
      name: "action",
      align: "left",
      label: "Hành động",
      field: "action",
    },
    
  ];
  
